version: '3.8'

services:
  # Application service
  app:
    image: ${APP_IMAGE:-app:latest}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  data:
    driver: local
