#!/bin/bash
#
# MCP Server 2 Startup Script
# This script runs on VM initialization and sets up the environment
#

set -e
set -x

# Log output
exec > >(tee /var/log/mcp-server-2-startup.log)
exec 2>&1

echo "=== MCP Server 2 Startup Script ==="
echo "Started at: $(date)"

# Update system
echo "Updating system packages..."
apt-get update
apt-get upgrade -y

# Install required packages
echo "Installing required packages..."
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    software-properties-common \
    git \
    jq \
    htop \
    vim \
    unzip

# Install Docker
echo "Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    usermod -aG docker $USER
    systemctl enable docker
    systemctl start docker
fi

# Install Docker Compose
echo "Installing Docker Compose..."
if ! command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_VERSION="2.23.0"
    curl -L "https://github.com/docker/compose/releases/download/v$${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
fi

# Mount additional disks
echo "Mounting additional disks..."
%{ for disk in additional_disks ~}
DISK_NAME="${disk.name}"
MOUNT_PATH="${disk.mount_path}"
DEVICE="/dev/disk/by-id/google-$${DISK_NAME}"

# Wait for disk to be available
timeout=30
counter=0
while [ ! -e "$DEVICE" ] && [ $counter -lt $timeout ]; do
    echo "Waiting for disk $DISK_NAME to be available..."
    sleep 2
    counter=$((counter + 1))
done

if [ -e "$DEVICE" ]; then
    # Check if disk has a filesystem
    if ! blkid "$DEVICE"; then
        echo "Formatting disk $DISK_NAME..."
        mkfs.ext4 -F "$DEVICE"
    fi
    
    # Create mount point
    mkdir -p "$MOUNT_PATH"
    
    # Mount disk
    mount "$DEVICE" "$MOUNT_PATH"
    
    # Add to fstab for persistence
    if ! grep -q "$DEVICE" /etc/fstab; then
        echo "$DEVICE $MOUNT_PATH ext4 defaults,nofail 0 2" >> /etc/fstab
    fi
    
    echo "Disk $DISK_NAME mounted at $MOUNT_PATH"
else
    echo "ERROR: Disk $DISK_NAME not found after $timeout seconds"
fi
%{ endfor ~}

# Install Tailscale
echo "Installing Tailscale..."
if ! command -v tailscale &> /dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi

# Authenticate Tailscale
echo "Authenticating Tailscale..."
tailscale up --authkey="${tailscale_authkey}" --accept-routes --advertise-tags=tag:mcp-server

# Clone MCP Server 2 repository
echo "Setting up MCP Server 2..."
MCP_DIR="/opt/mcp-server-2"
if [ ! -d "$MCP_DIR" ]; then
    mkdir -p "$MCP_DIR"
fi

# Create symbolic links to data disks
%{ for disk in additional_disks ~}
if [ -d "${disk.mount_path}" ]; then
    LINK_NAME=$(basename ${disk.mount_path})
    ln -sf "${disk.mount_path}" "$MCP_DIR/$LINK_NAME"
fi
%{ endfor ~}

# Set up environment file
cat > "$MCP_DIR/.env" <<'EOF'
# Generated by Terraform - DO NOT EDIT MANUALLY
DOMAIN=${domain}
TIMEZONE=America/Mexico_City

# PostgreSQL
POSTGRES_USER=mcpserver
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB_AUTHENTIK=authentik
POSTGRES_DB_KASM=kasm
POSTGRES_DB_INFISICAL=infisical
POSTGRES_DB_1PANEL=onepanel
POSTGRES_DB_WEBASSET=webasset

# Authentik
AUTHENTIK_SECRET_KEY=${authentik_secret_key}
AUTHENTIK_ERROR_REPORTING_ENABLED=false

# KasmWeb
KASM_ADMIN_PASSWORD=${kasm_admin_password}
KASM_SESSION_RECORDING_ENABLED=true

# Infisical
INFISICAL_ENCRYPTION_KEY=${infisical_encryption_key}

# Traefik
ACME_EMAIL=${acme_email}

# Tailscale
TAILSCALE_AUTHKEY=${tailscale_authkey}
EOF

chmod 600 "$MCP_DIR/.env"

# Create systemd service for MCP Server 2
cat > /etc/systemd/system/mcp-server-2.service <<EOF
[Unit]
Description=MCP Server 2 - KasmWeb Architecture
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$MCP_DIR
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Enable service
systemctl daemon-reload
systemctl enable mcp-server-2.service

# Configure firewall (ufw)
echo "Configuring firewall..."
apt-get install -y ufw
ufw --force enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    # SSH
ufw allow 80/tcp    # HTTP
ufw allow 443/tcp   # HTTPS
ufw allow 41641/udp # Tailscale

# Set up log rotation
cat > /etc/logrotate.d/mcp-server-2 <<EOF
/var/log/mcp-server-2-startup.log {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
}
EOF

# Set up automatic security updates
echo "Configuring automatic security updates..."
apt-get install -y unattended-upgrades
dpkg-reconfigure -plow unattended-upgrades

# Final message
echo "=== MCP Server 2 Startup Complete ==="
echo "Completed at: $(date)"
echo "Tailscale status:"
tailscale status
echo "Docker status:"
docker --version
docker-compose --version
echo ""
echo "Next steps:"
echo "1. Copy docker-compose.yml and configs to $MCP_DIR"
echo "2. Start services: systemctl start mcp-server-2"
echo "3. Check status: docker ps"
echo "4. View logs: docker-compose logs -f"
