name: Generate Infrastructure Diagrams

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

env:
  SCARF_ANALYTICS: false  # Disable analytics to prevent firewall blocks on scarf.sh

jobs:
  generate-diagrams:
    name: Generate Diagrams
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Generate Infrastructure Diagrams
        run: |
          cd diagrams
          chmod +x generate-diagrams.sh
          ./generate-diagrams.sh

      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure-diagrams
          path: diagrams/output/*.png
          retention-days: 30

      - name: Commit and Push Diagrams
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add diagrams/output/
          git diff --staged --quiet || git commit -m "📊 Update infrastructure diagrams [skip ci]"
          git push
